# -*- coding: utf-8 -*-
"""Streamlit Dashboard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1g1WDjDk40XkJCpuZfc6hC8Ip1WRw_LmG
"""

import streamlit as st
import pandas as pd
import streamlit.components.v1 as components

# Configure the Streamlit page layout to wide mode for dashboard aesthetics
st.set_page_config(
    page_title="Protein Structure Analysis",
    layout="wide",
    initial_sidebar_state="collapsed"
)

def inject_custom_css():
    st.markdown(
        """
        <style>
        /* Global styling tweaks */
        .block-container {
            padding-top: 2rem;
            padding-bottom: 2rem;
        }

        /* Top Navigation styling mock */
        .top-nav {
            display: flex;
            gap: 24px;
            padding-bottom: 1rem;
            border-bottom: 1px solid rgba(255, 255, 255, 0.1);
            margin-bottom: 2rem;
            font-size: 16px;
            font-weight: 500;
        }
        .top-nav a {
            color: inherit;
            text-decoration: none;
            cursor: pointer;
            opacity: 0.7;
            transition: opacity 0.2s;
        }
        .top-nav a.active {
            opacity: 1;
            border-bottom: 2px solid #4CAF50;
            padding-bottom: 4px;
        }
        .top-nav a:hover {
            opacity: 1;
        }

        /* Confidence Badge */
        .confidence-badge {
            background: linear-gradient(90deg, #1e3c72 0%, #2a5298 100%);
            color: white;
            padding: 12px 24px;
            border-radius: 8px;
            font-size: 1.2rem;
            font-weight: bold;
            display: inline-block;
            text-align: center;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
            border: 1px solid rgba(255,255,255,0.1);
            float: right;
        }

        /* Metric/Detail Item */
        .detail-item {
            display: flex;
            justify-content: space-between;
            padding: 8px 0;
            border-bottom: 1px solid rgba(255,255,255,0.05);
            font-size: 14px;
        }
        .detail-item:last-child {
            border-bottom: none;
        }
        .detail-label {
            opacity: 0.7;
            display: flex;
            align-items: center;
            gap: 4px;
        }
        .detail-value {
            font-weight: 600;
        }

        /* Validation Bars */
        .validation-row {
            display: flex;
            align-items: center;
            margin: 12px 0;
            font-size: 14px;
        }
        .validation-label {
            width: 140px;
            opacity: 0.8;
        }
        .validation-track {
            flex-grow: 1;
            height: 6px;
            background: rgba(255,255,255,0.1);
            border-radius: 4px;
            position: relative;
        }
        .validation-marker {
            position: absolute;
            top: -4px;
            width: 4px;
            height: 14px;
            border-radius: 2px;
            box-shadow: 0 0 4px rgba(0,0,0,0.5);
        }
        .marker-good { background: #4CAF50; }
        .marker-avg { background: #FFC107; }
        .marker-poor { background: #F44336; }

        /* Header titles */
        .header-title {
            font-size: 2.5rem;
            font-weight: 800;
            margin-bottom: 0;
            padding-bottom: 0;
            line-height: 1.2;
        }
        .header-subtitle {
            font-size: 1.2rem;
            opacity: 0.7;
            margin-top: 0;
            padding-top: 0;
            margin-bottom: 1.5rem;
        }
        </style>
        """,
        unsafe_allow_html=True
    )

inject_custom_css()

# Global Navigation (Mocked via HTML for visual fidelity)
st.markdown(
    """
    <div class="top-nav">
        <a class="active">Home</a>
        <a>About</a>
        <a>Contact Us</a>
    </div>
    """,
    unsafe_allow_html=True
)

col_h1, col_h2 = st.columns([3, 1])
with col_h1:
    st.markdown('<p class="header-title">6OSJ</p>', unsafe_allow_html=True)
    st.markdown('<p class="header-subtitle">Polymorph A Family</p>', unsafe_allow_html=True)

with col_h2:
    # Right-aligned confidence score
    st.markdown(
        '''
        <div style="display: flex; justify-content: flex-end; align-items: center; height: 100%;">
            <div class="confidence-badge">
                95% Confidence Score Match
            </div>
        </div>
        ''',
        unsafe_allow_html=True
    )

left_col, right_col = st.columns([1.7, 1], gap="large")

with left_col:
    # 1. 3D Viewer Placeholder
    st.subheader("3D Structure Viewer")

    # We use a custom HTML/CSS block to simulate an aesthetic PyMOL/stmol bounding box.
    # In production, replace this components.html call with stmol or py3Dmol.
    components.html(
        """
        <div style="
            width: 100%;
            height: 400px;
            background: linear-gradient(135deg, #1a1a1a 0%, #2d2d2d 100%);
            border-radius: 12px;
            border: 1px solid rgba(255,255,255,0.1);
            display: flex;
            flex-direction: column;
            justify-content: center;
            align-items: center;
            color: rgba(255,255,255,0.5);
            font-family: sans-serif;
            position: relative;
            overflow: hidden;
            box-shadow: inset 0 4px 20px rgba(0,0,0,0.3);
        ">
            <!-- Simulated protein mesh wireframe graphic -->
            <svg width="100" height="100" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round" style="opacity: 0.3; margin-bottom: 16px;">
                <path d="M2 12h4l3-9 5 18 3-9h5"/>
            </svg>
            <div style="font-size: 18px; font-weight: 600; color: rgba(255,255,255,0.7);">Interactive 3D Viewer Placeholder</div>
            <div style="font-size: 14px; margin-top: 8px;">(PyMOL / py3Dmol component goes here)</div>

            <!-- Mock controls overlay -->
            <div style="position: absolute; bottom: 16px; left: 16px; display: flex; gap: 8px;">
                <div style="padding: 6px 12px; background: rgba(0,0,0,0.4); border-radius: 4px; font-size: 12px;">Rotate</div>
                <div style="padding: 6px 12px; background: rgba(0,0,0,0.4); border-radius: 4px; font-size: 12px;">Zoom</div>
            </div>
        </div>
        """,
        height=420
    )

    st.write("") # Spacer

    # 2. Ranked Candidates Table
    st.subheader("All candidates, ranked by confidence")

    # Mock Data for the table
    candidates_data = {
        "Structure": ["6OSJ", "6XYO", "7L77", "8A99", "6ZXYZ"],
        "Polymorph": ["Polymorph A", "Polymorph A", "Polymorph B", "Twister", "MSA"],
        "Associated disease": ["Disease X", "Disease X", "Disease Y", "Disease Z", "Disease A"],
        "Confidence": [0.95, 0.88, 0.75, 0.60, 0.45],
        "Bounds": ["1-140", "1-140", "30-100", "10-120", "15-135"]
    }
    df_candidates = pd.DataFrame(candidates_data)

    # Display dataframe with custom column configurations
    st.dataframe(
        df_candidates,
        column_config={
            "Confidence": st.column_config.ProgressColumn(
                "Confidence",
                help="AI Confidence score match percentage",
                format="%.2f",
                min_value=0,
                max_value=1,
            ),
            "Structure": st.column_config.TextColumn("Structure", width="small"),
            "Bounds": st.column_config.TextColumn("Bounds", width="small")
        },
        hide_index=True,
        use_container_width=True
    )

with right_col:

    # Summary Text Expander
    with st.expander("About this Structure", expanded=True):
        st.write("""
        **6OSJ** is a high-resolution macromolecular structure classified into the Polymorph A Family.
        It represents a critical conformational state heavily associated with specific pathological aggregate formations.
        """)

    # Macromolecule Content Card
    with st.container(border=True):
        st.markdown('**Macromolecule Content**')
        # Using custom HTML for tight, aesthetic key-value pairs with mock tooltips (?)
        st.markdown(
            """
            <div class="detail-item">
                <div class="detail-label">Total Structure Weight <span title="Theoretical molecular weight" style="cursor:help; opacity:0.5;">?</span></div>
                <div class="detail-value">144.76 kDa</div>
            </div>
            <div class="detail-item">
                <div class="detail-label">Atom Count <span title="Total modeled atoms" style="cursor:help; opacity:0.5;">?</span></div>
                <div class="detail-value">1,240</div>
            </div>
            <div class="detail-item">
                <div class="detail-label">Modeled Residue Count <span title="Residues with resolved coordinates" style="cursor:help; opacity:0.5;">?</span></div>
                <div class="detail-value">140</div>
            </div>
            <div class="detail-item">
                <div class="detail-label">Deposited Residue Count</div>
                <div class="detail-value">140</div>
            </div>
            <div class="detail-item">
                <div class="detail-label">Unique protein chains</div>
                <div class="detail-value">1</div>
            </div>
            """,
            unsafe_allow_html=True
        )

    # Experimental Data & Validation Card
    with st.container(border=True):
        st.markdown('**Experimental Data**')
        st.markdown(
            """
            <div class="detail-item">
                <div class="detail-label">Method</div>
                <div class="detail-value">Electron Microscopy</div>
            </div>
            <div class="detail-item">
                <div class="detail-label">Resolution</div>
                <div class="detail-value">2.80 Å</div>
            </div>
            <div class="detail-item">
                <div class="detail-label">Aggregation State</div>
                <div class="detail-value">Fibril</div>
            </div>
            <div class="detail-item">
                <div class="detail-label">Reconstruction Method</div>
                <div class="detail-value">Helical</div>
            </div>
            """,
            unsafe_allow_html=True
        )

        st.write("") # Spacer
        st.markdown("<span style='font-size:14px; opacity:0.8;'>EM Software</span>", unsafe_allow_html=True)
        # Mock sub-table
        software_df = pd.DataFrame({
            "Task": ["Reconstruction", "Refinement"],
            "Package": ["RELION", "Phenix"],
            "Version": ["3.0", "1.18"]
        })
        st.dataframe(software_df, hide_index=True, use_container_width=True)

        # Actionable link placeholder
        st.markdown("[View more in-depth experimental data](#)")

    # Structure Validation Card
    with st.container(border=True):
        col_v1, col_v2 = st.columns([1, 1])
        with col_v1:
            st.markdown('**Structure Validation**')
        with col_v2:
            st.markdown("<div style='text-align: right;'><a href='#' style='font-size: 14px;'>Full Validation Report</a></div>", unsafe_allow_html=True)

        # Custom percentile ranking bars
        # Left side is 0 (poor), right side is 100 (good)
        st.markdown(
            """
            <div class="validation-row">
                <div class="validation-label">Clashscore</div>
                <div class="validation-track"><div class="validation-marker marker-good" style="left: 90%;"></div></div>
            </div>
            <div class="validation-row">
                <div class="validation-label">Ramachandran out.</div>
                <div class="validation-track"><div class="validation-marker marker-good" style="left: 98%;"></div></div>
            </div>
            <div class="validation-row">
                <div class="validation-label">Sidechain outliers</div>
                <div class="validation-track"><div class="validation-marker marker-avg" style="left: 70%;"></div></div>
            </div>
            <div class="validation-row">
                <div class="validation-label">Q-score</div>
                <div class="validation-track"><div class="validation-marker marker-poor" style="left: 45%;"></div></div>
            </div>
            <div style="display:flex; justify-content:space-between; font-size:10px; opacity:0.5; margin-top:4px;">
                <span>Worse</span>
                <span>Better</span>
            </div>
            """,
            unsafe_allow_html=True
        )

    st.write("") # Spacer
    st.button("Run test again", type="primary", use_container_width=True)
